//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPackage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpProducts
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortRemarks { get; set; }
        public string PageView { get; set; }
        public string PgFeatureImg { get; set; }
        public int Sort { get; set; }
        public int tpAreasId { get; set; }
    
        public virtual tpAreas tpArea { get; set; }
    }
}
